### ISSUE TITLE
Records get proxied even though they are set to proxied: false

### ISSUE THREAD

**Issue by Fernien** [jmrplens/DynDNS_Cloudflare_IPv4-6#101]
Hey,

i just used your script to update my DNS records. Even though i made these entries in the yaml file:
```
# Global settings (applied to all domains unless overridden)
globals:
  ipv4: true
  ipv6: true
  proxied: false
  ttl: auto
  enable_create_record: true

# Domain-specific settings
domains:
  - name: "*.guenauer.de"
    ipv4: true
    ipv6: true
    proxied: false
    ttl: 300
```

after running cloudflare-dns.sh update  it returned this and proxied the record:

```
========================= DOMAINS TO BE PROCESSED =========================
 1. *.example.com   -> IPv4, IPv6, Proxied, TTL: 300
```

Why is it proxying the records?
Best,
Niklas
